#!/bin/sh
# This script is used to update the typescript bindings for the project.
# It is used by the CI system to ensure that the bindings are up to date (on PR/merge/push).
# It can also be used locally to update the bindings.

# This script requires the following tools to be installed:
# - cargo
# - pnpm

rm -rf ./bindings

# Running `test --all-features` will also generate bindings via `ts-rs` however they are not
# formatted nicely. So we then run prettier to format them.
cargo test --all-features

# Ensure that the generated bindings are formatted nicely.
npx prettier --write ./bindings/*.ts
