export type BiomeItem = { value: string; label: string; disabled: boolean };
export const BIOMES: BiomeItem[] = [
  { disabled: false, value: 'MOUNTAIN', label: 'Mountain' },
  { disabled: false, value: 'MOUNTAINS', label: 'Mountains' },
  { disabled: false, value: 'GLACIER', label: 'Glacier' },
  { disabled: false, value: 'TUNDRA', label: 'Tundra' },
  { disabled: false, value: 'SWAMP_TEMPERATE_FRESHWATER', label: 'Temperate Freshwater Swamp' },
  { disabled: false, value: 'SWAMP_TEMPERATE_SALTWATER', label: 'Temperate Saltwater Swamp' },
  { disabled: false, value: 'MARSH_TEMPERATE_FRESHWATER', label: 'Temperate Freshwater Marsh' },
  { disabled: false, value: 'MARSH_TEMPERATE_SALTWATER', label: 'Temperate Saltwater Marsh' },
  { disabled: false, value: 'SWAMP_TROPICAL_FRESHWATER', label: 'Tropical Freshwater Swamp' },
  { disabled: false, value: 'SWAMP_TROPICAL_SALTWATER', label: 'Tropical Saltwater Swamp' },
  { disabled: false, value: 'SWAMP_MANGROVE', label: 'Mangrove Swamp' },
  { disabled: false, value: 'MARSH_TROPICAL_FRESHWATER', label: 'Tropical Freshwater Marsh' },
  { disabled: false, value: 'MARSH_TROPICAL_SALTWATER', label: 'Tropical Saltwater Marsh' },
  { disabled: false, value: 'FOREST_TAIGA', label: 'Taiga Forest' },
  { disabled: false, value: 'TAIGA', label: 'Taiga' },
  { disabled: false, value: 'FOREST_TEMPERATE_CONIFER', label: 'Temperate Coniferous Forest' },
  { disabled: false, value: 'FOREST_TEMPERATE_BROADLEAF', label: 'Temperate Broadleaf Forest' },
  { disabled: false, value: 'FOREST_TROPICAL_CONIFER', label: 'Tropical Coniferous Forest' },
  { disabled: false, value: 'FOREST_TROPICAL_DRY_BROADLEAF', label: 'Tropical Dry Broadleaf Forest' },
  { disabled: false, value: 'FOREST_TROPICAL_MOIST_BROADLEAF', label: 'Tropical Moist Broadleaf Forest' },
  { disabled: false, value: 'GRASSLAND_TEMPERATE', label: 'Temperate Grassland' },
  { disabled: false, value: 'SAVANNA_TEMPERATE', label: 'Temperate Savanna' },
  { disabled: false, value: 'SHRUBLAND_TEMPERATE', label: 'Temperate Shrubland' },
  { disabled: false, value: 'GRASSLAND_TROPICAL', label: 'Tropical Grassland' },
  { disabled: false, value: 'SAVANNA_TROPICAL', label: 'Tropical Savanna' },
  { disabled: false, value: 'SHRUBLAND_TROPICAL', label: 'Tropical Shrubland' },
  { disabled: false, value: 'DESERT_BADLAND', label: 'Badlands' },
  { disabled: false, value: 'DESERT_ROCK', label: 'Rocky Wasteland' },
  { disabled: false, value: 'DESERT_SAND', label: 'Sand Desert' },
  { disabled: false, value: 'OCEAN_TROPICAL', label: 'Tropical Ocean' },
  { disabled: false, value: 'OCEAN_TEMPERATE', label: 'Temperate Ocean' },
  { disabled: false, value: 'OCEAN_ARCTIC', label: 'Arctic Ocean' },
  { disabled: false, value: 'POOL_TEMPERATE_FRESHWATER', label: 'Temperate Freshwater Pool' },
  { disabled: false, value: 'POOL_TEMPERATE_BRACKISHWATER', label: 'Temperate Brackish Pool' },
  { disabled: false, value: 'POOL_TEMPERATE_SALTWATER', label: 'Temperate Saltwater Pool' },
  { disabled: false, value: 'POOL_TROPICAL_FRESHWATER', label: 'Tropical Freshwater Pool' },
  { disabled: false, value: 'POOL_TROPICAL_BRACKISHWATER', label: 'Tropical Brackish Pool' },
  { disabled: false, value: 'POOL_TROPICAL_SALTWATER', label: 'Tropical Saltwater Pool' },
  { disabled: false, value: 'LAKE_TEMPERATE_FRESHWATER', label: 'Temperate Freshwater Lake' },
  { disabled: false, value: 'LAKE_TEMPERATE_BRACKISHWATER', label: 'Temperate Brackish Lake' },
  { disabled: false, value: 'LAKE_TEMPERATE_SALTWATER', label: 'Temperate Saltwater Lake' },
  { disabled: false, value: 'LAKE_TROPICAL_FRESHWATER', label: 'Tropical Freshwater Lake' },
  { disabled: false, value: 'LAKE_TROPICAL_BRACKISHWATER', label: 'Tropical Brackish Lake' },
  { disabled: false, value: 'LAKE_TROPICAL_SALTWATER', label: 'Tropical Saltwater Lake' },
  { disabled: false, value: 'RIVER_TEMPERATE_FRESHWATER', label: 'Temperate Freshwater River' },
  { disabled: false, value: 'RIVER_TEMPERATE_BRACKISHWATER', label: 'Temperate Brackish River' },
  { disabled: false, value: 'RIVER_TEMPERATE_SALTWATER', label: 'Temperate Saltwater River' },
  { disabled: false, value: 'RIVER_TROPICAL_FRESHWATER', label: 'Tropical Freshwater River' },
  { disabled: false, value: 'RIVER_TROPICAL_BRACKISHWATER', label: 'Tropical Brackish River' },
  { disabled: false, value: 'RIVER_TROPICAL_SALTWATER', label: 'Tropical Saltwater River' },
  { disabled: false, value: 'SUBTERRANEAN_WATER', label: 'Underground caverns (in water)' },
  { disabled: false, value: 'SUBTERRANEAN_CHASM', label: 'Underground caverns (out of water)' },
  { disabled: false, value: 'SUBTERRANEAN_LAVA', label: 'Magma sea' },
  { disabled: false, value: 'ALL_MAIN', label: 'All biomes excluding pools, rivers, and underground features' },
  { disabled: false, value: 'ANY_LAND', label: 'All main biomes excluding oceans and lakes' },
  { disabled: false, value: 'ANY_OCEAN', label: 'All ocean biomes' },
  { disabled: false, value: 'ANY_LAKE', label: 'All lake biomes' },
  { disabled: false, value: 'ANY_TEMPERATE_LAKE', label: 'All temperate lake biomes' },
  { disabled: false, value: 'ANY_TROPICAL_LAKE', label: 'All tropical lake biomes' },
  { disabled: false, value: 'ANY_RIVER', label: 'All river biomes' },
  { disabled: false, value: 'ANY_TEMPERATE_RIVER', label: 'All temperate river biomes' },
  { disabled: false, value: 'ANY_TROPICAL_RIVER', label: 'All tropical river biomes' },
  { disabled: false, value: 'ANY_POOL', label: 'All pool biomes' },
  { disabled: false, value: 'NOT_FREEZING', label: 'All land biomes excluding Mountain, Glacier, and Tundra' },
  {
    disabled: false,
    value: 'ANY_TEMPERATE',
    label: 'All Temperate land biomes - marshes, swamps, forests, grassland, savanna, and shrubland',
  },
  {
    disabled: false,
    value: 'ANY_TROPICAL',
    label:
      'All Tropical land biomes - marshes, swamps (including Mangrove), forests, grassland, savanna, and shrubland',
  },
  { disabled: false, value: 'ANY_FOREST', label: 'All Forest biomes (excluding Taiga)' },
  { disabled: false, value: 'ANY_SHRUBLAND', label: 'Temperate and Tropical Shrubland' },
  { disabled: false, value: 'ANY_GRASSLAND', label: 'Temperate and Tropical Grassland' },
  { disabled: false, value: 'ANY_SAVANNA', label: 'Temperate and Tropical Savanna' },
  { disabled: false, value: 'ANY_TEMPERATE_FOREST', label: 'Temperate Coniferous and Broadleaf Forests' },
  { disabled: false, value: 'ANY_TROPICAL_FOREST', label: 'Tropical Coniferous and Dry/Moist Broadleaf Forests' },
  {
    disabled: false,
    value: 'ANY_TEMPERATE_BROADLEAF',
    label: 'Temperate Broadleaf Forest, Grassland/Savanna/Shrubland, Swamps, and Marshes',
  },
  {
    disabled: false,
    value: 'ANY_TROPICAL_BROADLEAF',
    label: 'Tropical Dry/Moist Broadleaf Forest, Grassland/Savanna/Shrubland, Swamps (including Mangrove), and Marshes',
  },
  { disabled: false, value: 'ANY_WETLAND', label: 'All swamps and marshes' },
  { disabled: false, value: 'ANY_TEMPERATE_WETLAND', label: 'All temperate swamps and marshes' },
  { disabled: false, value: 'ANY_TROPICAL_WETLAND', label: 'All tropical swamps and marshes' },
  { disabled: false, value: 'ANY_TROPICAL_MARSH', label: 'All tropical marshes' },
  { disabled: false, value: 'ANY_TEMPERATE_MARSH', label: 'All temperate marshes' },
  { disabled: false, value: 'ANY_TROPICAL_SWAMP', label: 'All tropical swamps (including Mangrove)' },
  { disabled: false, value: 'ANY_TEMPERATE_SWAMP', label: 'All temperate swamps' },
  { disabled: false, value: 'ANY_DESERT', label: 'Badlands, Rocky Wasteland, and Sand Desert' },
];
