import type { Biome } from "../../src-tauri/bindings/Bindings";
// BiomeItem is used for the Combobox component which is used to select biomes.
export type BiomeItem = { value: Biome; label: string; disabled: boolean };

// This is just hardcoded biome information. Value corresponds to the string token
// which would be in the raws as part of the biome tag (e.g. `[BIOME:MOUNTAIN]`).
// The value is not an exact match for the raws, because the backend has already
// parsed and "cleaned up" the token.
// The label is the human-readable name for the biome, and the disabled flag will
// disable the biome in the Combobox component.
export const BIOMES: BiomeItem[] = [
	{ disabled: false, value: "Mountain", label: "Mountain" },
	{ disabled: false, value: "Mountains", label: "Mountains" },
	{ disabled: false, value: "Glacier", label: "Glacier" },
	{ disabled: false, value: "Tundra", label: "Tundra" },
	{ disabled: false, value: "SwampTemperateFreshwater", label: "Temperate Freshwater Swamp" },
	{ disabled: false, value: "SwampTemperateSaltwater", label: "Temperate Saltwater Swamp" },
	{ disabled: false, value: "MarshTemperateFreshwater", label: "Temperate Freshwater Marsh" },
	{ disabled: false, value: "MarshTemperateSaltwater", label: "Temperate Saltwater Marsh" },
	{ disabled: false, value: "SwampTropicalFreshwater", label: "Tropical Freshwater Swamp" },
	{ disabled: false, value: "SwampTropicalSaltwater", label: "Tropical Saltwater Swamp" },
	{ disabled: false, value: "SwampMangrove", label: "Mangrove Swamp" },
	{ disabled: false, value: "MarshTropicalFreshwater", label: "Tropical Freshwater Marsh" },
	{ disabled: false, value: "MarshTropicalSaltwater", label: "Tropical Saltwater Marsh" },
	{ disabled: false, value: "ForestTaiga", label: "Taiga Forest" },
	{ disabled: false, value: "Taiga", label: "Taiga" },
	{ disabled: false, value: "ForestTemperateConifer", label: "Temperate Coniferous Forest" },
	{ disabled: false, value: "ForestTemperateBroadleaf", label: "Temperate Broadleaf Forest" },
	{ disabled: false, value: "ForestTropicalConifer", label: "Tropical Coniferous Forest" },
	{ disabled: false, value: "ForestTropicalDryBroadleaf", label: "Tropical Dry Broadleaf Forest" },
	{ disabled: false, value: "ForestTropicalMoistBroadleaf", label: "Tropical Moist Broadleaf Forest" },
	{ disabled: false, value: "GrasslandTemperate", label: "Temperate Grassland" },
	{ disabled: false, value: "SavannaTemperate", label: "Temperate Savanna" },
	{ disabled: false, value: "ShrublandTemperate", label: "Temperate Shrubland" },
	{ disabled: false, value: "GrasslandTropical", label: "Tropical Grassland" },
	{ disabled: false, value: "SavannaTropical", label: "Tropical Savanna" },
	{ disabled: false, value: "ShrublandTropical", label: "Tropical Shrubland" },
	{ disabled: false, value: "DesertBadland", label: "Badlands" },
	{ disabled: false, value: "DesertRock", label: "Rocky Wasteland" },
	{ disabled: false, value: "DesertSand", label: "Sand Desert" },
	{ disabled: false, value: "OceanTropical", label: "Tropical Ocean" },
	{ disabled: false, value: "OceanTemperate", label: "Temperate Ocean" },
	{ disabled: false, value: "OceanArctic", label: "Arctic Ocean" },
	{ disabled: false, value: "PoolTemperateFreshwater", label: "Temperate Freshwater Pool" },
	{ disabled: false, value: "PoolTemperateBrackishwater", label: "Temperate Brackish Pool" },
	{ disabled: false, value: "PoolTemperateSaltwater", label: "Temperate Saltwater Pool" },
	{ disabled: false, value: "PoolTropicalFreshwater", label: "Tropical Freshwater Pool" },
	{ disabled: false, value: "PoolTropicalBrackishwater", label: "Tropical Brackish Pool" },
	{ disabled: false, value: "PoolTropicalSaltwater", label: "Tropical Saltwater Pool" },
	{ disabled: false, value: "LakeTemperateFreshwater", label: "Temperate Freshwater Lake" },
	{ disabled: false, value: "LakeTemperateBrackishwater", label: "Temperate Brackish Lake" },
	{ disabled: false, value: "LakeTemperateSaltwater", label: "Temperate Saltwater Lake" },
	{ disabled: false, value: "LakeTropicalFreshwater", label: "Tropical Freshwater Lake" },
	{ disabled: false, value: "LakeTropicalBrackishwater", label: "Tropical Brackish Lake" },
	{ disabled: false, value: "LakeTropicalSaltwater", label: "Tropical Saltwater Lake" },
	{ disabled: false, value: "RiverTemperateFreshwater", label: "Temperate Freshwater River" },
	{ disabled: false, value: "RiverTemperateBrackishwater", label: "Temperate Brackish River" },
	{ disabled: false, value: "RiverTemperateSaltwater", label: "Temperate Saltwater River" },
	{ disabled: false, value: "RiverTropicalFreshwater", label: "Tropical Freshwater River" },
	{ disabled: false, value: "RiverTropicalBrackishwater", label: "Tropical Brackish River" },
	{ disabled: false, value: "RiverTropicalSaltwater", label: "Tropical Saltwater River" },
	{ disabled: false, value: "SubterraneanWater", label: "Underground caverns (in water)" },
	{ disabled: false, value: "SubterraneanChasm", label: "Underground caverns (out of water)" },
	{ disabled: false, value: "SubterraneanLava", label: "Magma sea" },
	{ disabled: false, value: "AllMain", label: "All biomes excluding pools, rivers, and underground features" },
	{ disabled: false, value: "AnyLand", label: "All main biomes excluding oceans and lakes" },
	{ disabled: false, value: "AnyOcean", label: "All ocean biomes" },
	{ disabled: false, value: "AnyLake", label: "All lake biomes" },
	{ disabled: false, value: "AnyTemperateLake", label: "All temperate lake biomes" },
	{ disabled: false, value: "AnyTropicalLake", label: "All tropical lake biomes" },
	{ disabled: false, value: "AnyRiver", label: "All river biomes" },
	{ disabled: false, value: "AnyTemperateRiver", label: "All temperate river biomes" },
	{ disabled: false, value: "AnyTropicalRiver", label: "All tropical river biomes" },
	{ disabled: false, value: "AnyPool", label: "All pool biomes" },
	{ disabled: false, value: "NotFreezing", label: "All land biomes excluding Mountain, Glacier, and Tundra" },
	{
		disabled: false,
		value: "AnyTemperate",
		label: "All Temperate land biomes - marshes, swamps, forests, grassland, savanna, and shrubland",
	},
	{
		disabled: false,
		value: "AnyTropical",
		label: "All Tropical land biomes - marshes, swamps (including Mangrove), forests, grassland, savanna, and shrubland",
	},
	{ disabled: false, value: "AnyForest", label: "All Forest biomes (excluding Taiga)" },
	{ disabled: false, value: "AnyShrubland", label: "Temperate and Tropical Shrubland" },
	{ disabled: false, value: "AnyGrassland", label: "Temperate and Tropical Grassland" },
	{ disabled: false, value: "AnySavanna", label: "Temperate and Tropical Savanna" },
	{ disabled: false, value: "AnyTemperateForest", label: "Temperate Coniferous and Broadleaf Forests" },
	{ disabled: false, value: "AnyTropicalForest", label: "Tropical Coniferous and Dry/Moist Broadleaf Forests" },
	{
		disabled: false,
		value: "AnyTemperateBroadleaf",
		label: "Temperate Broadleaf Forest, Grassland/Savanna/Shrubland, Swamps, and Marshes",
	},
	{
		disabled: false,
		value: "AnyTropicalBroadleaf",
		label: "Tropical Dry/Moist Broadleaf Forest, Grassland/Savanna/Shrubland, Swamps (including Mangrove), and Marshes",
	},
	{ disabled: false, value: "AnyWetland", label: "All swamps and marshes" },
	{ disabled: false, value: "AnyTemperateWetland", label: "All temperate swamps and marshes" },
	{ disabled: false, value: "AnyTropicalWetland", label: "All tropical swamps and marshes" },
	{ disabled: false, value: "AnyTropicalMarsh", label: "All tropical marshes" },
	{ disabled: false, value: "AnyTemperateMarsh", label: "All temperate marshes" },
	{ disabled: false, value: "AnyTropicalSwamp", label: "All tropical swamps (including Mangrove)" },
	{ disabled: false, value: "AnyTemperateSwamp", label: "All temperate swamps" },
	{ disabled: false, value: "AnyDesert", label: "Badlands, Rocky Wasteland, and Sand Desert" },
];
