branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - verifyRelease: bash version ${nextRelease.version} dry-run
      prepareCmd: bash version ${nextRelease.version}
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
      message: "chore: release ${nextRelease.version}\n\n${nextRelease.notes}"
  - semantic-release-export-data
  - "@semantic-release/github"
