// This file was auto-generated by tauri-ts-generator
// This file was manually edited: Do not overwrite

import { invoke } from "@tauri-apps/api/core";
import type {
  DbOptionOnParse,
  GraphicsResult,
  StoredSettings,
} from "./Structs";
import type {
  Dimensions,
  LocationHelper,
  ParserOptions,
  RawModuleLocation,
  RawObject,
  SearchQuery,
  SearchResults,
} from "./DFRawParser";

export async function getGraphics(
  identifier: string,
  viewport: Dimensions | null,
): Promise<GraphicsResult[]> {
  return invoke<GraphicsResult[]>("get_graphics", { identifier, viewport });
}

export async function parseRaws(
  directories: LocationHelper,
  locations: RawModuleLocation[],
  dbOption: DbOptionOnParse,
): Promise<string> {
  return invoke<string>("parse_raws", {
    directories,
    locations,
    dbOption,
  });
}

export async function getRawById(id: string): Promise<RawObject> {
  return invoke<RawObject>("get_raw_by_id", { id });
}

export async function searchRaws(
  query: SearchQuery,
): Promise<SearchResults<RawObject>> {
  return invoke<SearchResults<RawObject>>("search_raws", { query });
}

export async function retrieveDwarfFortressDirectory(): Promise<string> {
  return invoke<string>("retrieve_dwarf_fortress_directory");
}

export async function retrieveUserDataDirectory(): Promise<string> {
  return invoke<string>("retrieve_user_data_directory");
}

export async function retrieveParserOptions(): Promise<ParserOptions> {
  return invoke<ParserOptions>("retrieve_parser_options");
}

export async function retrieveStoredSettings(): Promise<StoredSettings> {
  return invoke<StoredSettings>("retrieve_stored_settings");
}

export async function persistStoredSettings(
  settings: StoredSettings,
): Promise<void> {
  return invoke<void>("persist_stored_settings", { settings });
}

export async function retrieveLastParseDuration(): Promise<string> {
  return invoke<string>("retrieve_last_parse_duration");
}

export async function retrieveLastInsertionDuration(): Promise<string> {
  return invoke<string>("retrieve_last_insertion_duration");
}

export async function retrieveRecentSearchTerms(): Promise<string[]> {
  return invoke<string[]>("retrieve_recent_search_terms");
}

export async function retrieveFavoriteRaws(): Promise<string[]> {
  return invoke<string[]>("retrieve_favorite_raws");
}

export async function addFavoriteRaw(raw_id: string): Promise<string> {
  return invoke<string>("add_favorite_raw", { raw_id });
}

export async function removeFavoriteRaw(raw_id: string): Promise<string> {
  return invoke<string>("remove_favorite_raw", { raw_id });
}

export async function persistPreferredSearchLimit(
  limit: number,
): Promise<number> {
  return invoke<number>("persist_preferred_search_limit", { limit });
}

export async function retrievePreferredSearchLimit(): Promise<number> {
  return invoke<number>("retrieve_preferred_search_limit");
}

export async function retrieveLastInsertionDate(): Promise<string> {
  return invoke<string>("retrieve_last_insertion_date");
}

export async function retrieveLastParseOperationDate(): Promise<string> {
  return invoke<string>("retrieve_last_parse_operation_date");
}
