// This file was auto-generated by tauri-ts-generator
// This file was manually edited: Do not overwrite

import { invoke } from "@tauri-apps/api/core";
import type { DbOptionOnParse, GraphicsResult } from "./Structs";
import type {
  LocationHelper,
  RawModuleLocation,
  RawObject,
  SearchQuery,
  SearchResults,
} from "./DFRawParser";

export async function getGraphics(
  identifier: string,
): Promise<GraphicsResult[]> {
  return invoke<GraphicsResult[]>("get_graphics", { identifier });
}

export async function parseRaws(
  directories: LocationHelper,
  locations: RawModuleLocation[],
  dbOption: DbOptionOnParse,
): Promise<string> {
  return invoke<string>("parse_raws", {
    directories,
    locations,
    dbOption,
  });
}

export async function getRawById(id: string): Promise<RawObject> {
  return invoke<RawObject>("get_raw_by_id", { id });
}

export async function searchRaws(
  query: SearchQuery,
): Promise<SearchResults<RawObject>> {
  return invoke<SearchResults<RawObject>>("search_raws", { query });
}
