// This file was auto-generated by tauri-ts-generator
// This file was manually edited: Do not overwrite

import type { Dimensions } from "./DFRawParser";

export interface GraphicsResult {
  filePath: string;
  offset: Dimensions;
  offset2: Dimensions | null;
  tileDimensions: Dimensions;
  pageDimensions: Dimensions;
  description: string;
  positionOffset: Dimensions;
}

export type DbOptionOnParse = "insertOnly" | "forceUpdate" | "reset";
