// This file was auto-generated by tauri-ts-generator
// This file was manually edited: Do not overwrite

import type { Dimensions, RawModuleLocation } from "./DFRawParser";

export interface GraphicsResult {
  filePath: string;
  bgSize: string;
  bgPosition: string;
  aspectRatio: Dimensions;
  offset: Dimensions;
  offset2: Dimensions | null;
  tileDimensions: Dimensions;
  pageDimensions: Dimensions;
  description: string;
  positionOffset: Dimensions;
  targetIdentifier: string;
}

export type DbOptionOnParse = "insertOnly" | "forceUpdate" | "reset";

export const PARSING_EVENT_LOG = "parsing-log";

export type LogLevel = "trace" | "debug" | "info" | "warn" | "error" | "panic";

export interface ParsingEventPayload {
  level: LogLevel;
  message: string;
}

export interface StoredSettings {
  dfDirectory: string | null;
  userDirectory: string | null;
  parseLocations: RawModuleLocation[];
  databaseLocation: string;
  randomizeImageRotation: boolean;
  enableDirectoryDetection: boolean;
  startupAction: string;
}
