// This file was auto-generated by tauri-ts-generator
// Do not edit this file manually

import type { SpriteGraphicData, TilePageData } from "./DFRawParser";

export interface GraphicsResults {
  matchingGraphics: SpriteGraphicData[];
  tilePages: TilePageData[];
}
