#[test]
fn generate_ts_bindings() {
    // get our current working directory
    let cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
    // set lib/bindings as the output directory
    let output_dir = cwd.join("bindings");
    // make sure output dir exists
    if let Err(e) = std::fs::create_dir_all(&output_dir) {
        eprintln!("Failed to create output directory: {e}");
        return;
    }

    // Create a config to use for the specta::ts::export function
    let config = specta::ts::ExportConfiguration::default()
        .export_by_default(Some(true))
        .bigint(specta::ts::BigIntExportBehavior::String);

    let bindings: Vec<String> = vec![
        export_type::<app_lib::search_handler::options::SearchOptions>(&config),
        // Note that search_handler::results::SearchResults is not exported because it contains a Box<dyn RawObject>
        // which cannot be exported to TypeScript.
        //
        export_type::<app_lib::search_handler::summary::Summary>(&config),
        export_type::<app_lib::graphics::options::GraphicsOptions>(&config),
        export_type::<app_lib::graphics::results::GraphicsResults>(&config),
        // Note that state::Storage is not exported because it contains a Box<dyn RawObject> which cannot be exported.
        //
        export_type::<app_lib::state::GraphicStorage>(&config),
        export_type::<app_lib::state::ModuleInfoStorage>(&config),
        export_type::<app_lib::info::Info>(&config),
        export_type::<app_lib::tracking::ParseAllRawsInfo>(&config),
        export_type::<app_lib::tracking::ParseAndStoreRaws>(&config),
        export_type::<app_lib::tracking::SkipUpdate>(&config),
        export_type::<app_lib::tracking::ApplyUpdate>(&config),
        export_type::<app_lib::tracking::AppStarted>(&config),
        export_type::<app_lib::tracking::AppExited>(&config),
        // Types used from dfraw_json_parser
        export_type::<dfraw_json_parser::ObjectType>(&config),
        export_type::<dfraw_json_parser::ParserOptions>(&config),
        export_type::<dfraw_json_parser::parser::Color>(&config),
        export_type::<dfraw_json_parser::parser::ModuleInfoFile>(&config),
        export_type::<dfraw_json_parser::parser::RawMetadata>(&config),
        export_type::<dfraw_json_parser::parser::RawModuleLocation>(&config),
        export_type::<dfraw_json_parser::parser::SteamData>(&config),
        export_type::<dfraw_json_parser::parser::biome::Token>(&config),
        export_type::<dfraw_json_parser::parser::graphics::Graphic>(&config),
        export_type::<dfraw_json_parser::parser::graphics::TilePage>(&config),
        export_type::<dfraw_json_parser::parser::graphics::GraphicTypeToken>(&config),
        export_type::<dfraw_json_parser::parser::graphics::SpriteGraphic>(&config),
        export_type::<dfraw_json_parser::parser::graphics::SpriteLayer>(&config),
        export_type::<dfraw_json_parser::parser::graphics::CustomGraphicExtension>(&config),
        export_type::<dfraw_json_parser::parser::graphics::Dimensions>(&config),
        export_type::<dfraw_json_parser::parser::graphics::ConditionToken>(&config),
        export_type::<dfraw_json_parser::parser::graphics::ColorModificationToken>(&config),
    ];

    write_bindings(
        &output_dir,
        bindings
            .iter()
            .map(std::string::String::as_str)
            .collect::<Vec<&str>>()
            .as_slice(),
    );
}

fn header(struct_path: &str) -> String {
    format!("// File generated by specta. Do not edit!\n//\n/// lib/{struct_path}\n\n")
}

fn export_type<T: std::fmt::Debug + specta::NamedType>(
    config: &specta::ts::ExportConfiguration,
) -> String {
    match specta::ts::export::<T>(config) {
        Ok(x) => x,
        Err(e) => {
            tracing::error!("{:?}", e);
            String::new()
        }
    }
}

fn write_bindings(output_dir: &std::path::Path, bindings: &[&str]) {
    // write the bindings to the output file
    match std::fs::write(
        output_dir
            .join("Bindings.d.ts")
            .as_os_str()
            .to_str()
            .unwrap_or_default(),
        format!(
            "{}\n{}",
            header("overseers_manual_df"),
            &bindings.join("\n")
        ),
    ) {
        Err(e) => {
            tracing::error!("{e:?}");
            tracing::error!("Failed to write bindings to file");
        }
        Ok(()) => {
            tracing::info!("Wrote bindings to file");
        }
    }
}
