use specta::ts::{export, BigIntExportBehavior, ExportConfig};

fn header(struct_path: &str) -> String {
    format!("// File generated by specta. Do not edit!\n//\n/// lib/{struct_path}\n\n")
}

struct TypescriptBinding {
    output_path: std::path::PathBuf,
}

impl TypescriptBinding {
    fn new(output_path: std::path::PathBuf) -> Self {
        Self { output_path }
    }

    fn write(&self, struct_path: &str, bindings_filename: &str, imports: Option<String>, x: &str) {
        match std::fs::write(
            self.output_path
                .join(bindings_filename)
                .as_os_str()
                .to_str()
                .unwrap_or_default(),
            format!(
                "{}\n{}\n{}",
                header(struct_path),
                imports.unwrap_or_default(),
                &x
            ),
        ) {
            Err(e) => {
                eprintln!("{e:?}");
                eprintln!("Failed to write bindings for {struct_path} to {bindings_filename}");
            }
            Ok(()) => {
                println!("Wrote bindings for {struct_path} to {bindings_filename}");
            }
        }
    }
}

#[test]
#[allow(clippy::too_many_lines)]
fn generate_ts_bindings() {
    // get our current working directory
    let cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
    // set lib/bindings as the output directory
    let output_dir = cwd.join("bindings");
    // make sure output dir exists
    if let Err(e) = std::fs::create_dir_all(&output_dir) {
        eprintln!("Failed to create output directory: {e}");
        return;
    }

    let ts_bindings = TypescriptBinding::new(output_dir);
    let config = ExportConfig::default().bigint(BigIntExportBehavior::String);

    let bindings: Vec<String> = vec![
        match export::<app_lib::search_handler::options::SearchOptions>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::SearchOptions");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<app_lib::search_handler::filtering::Filter>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::Filter");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<app_lib::search_handler::filtering::SearchFilter>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::SearchFilter");
                eprintln!("{e:?}");
                String::new()
            }
        },
        // Note that search_handler::results::SearchResults is not exported because it contains a Box<dyn RawObject>
        // which cannot be exported to TypeScript.
        //
        match export::<app_lib::search_handler::summary::Summary>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::Summary");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<app_lib::graphics::options::GraphicsOptions>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::GraphicsOptions");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<app_lib::graphics::results::GraphicsResults>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::GraphicsResults");
                eprintln!("{e:?}");
                String::new()
            }
        },
        // Note that state::Storage is not exported because it contains a Box<dyn RawObject> which cannot be exported.
        //
        match export::<app_lib::state::GraphicStorage>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::GraphicStorage");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<app_lib::state::ModuleInfoStorage>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::ModuleInfoStorage");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<app_lib::info::Info>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::Info");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<app_lib::tracking::ParseAllRawsInfo>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::ParseAllRawsInfo");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<app_lib::tracking::ParseAndStoreRaws>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::ParseAndStoreRaws");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<app_lib::tracking::SkipUpdate>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::SkipUpdate");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<app_lib::tracking::ApplyUpdate>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::ApplyUpdate");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<app_lib::tracking::AppStarted>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::AppStarted");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<app_lib::tracking::AppExited>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export app_lib::AppExited");
                eprintln!("{e:?}");
                String::new()
            }
        },
        // Types used from dfraw_json_parser
        match export::<dfraw_json_parser::tags::BiomeTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export biome::Token");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Creature>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export creature::Creature");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::CreatureTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export creature::Token");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Gait>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export creature_caste::Gait");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::GaitTypeTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export creature_caste::GaitType");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::GaitModifierTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export creature_caste::GaitModifier");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::CasteTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export creature_caste::Token");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Caste>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export creature_caste::Caste");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::CreatureEffectPropertyTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export creature_effect::PropertyToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::CreatureEffectTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export creature_effect::Token");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::CreatureVariation>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export creature_variation::CreatureVariation");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::CreatureVariationRuleTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export creature_variation::Rule");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::CreatureVariationTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export creature_variation::Token");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Entity>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export entity::Entity");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::EntityTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export entity::Token");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Graphic>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export graphics::Graphic");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::SpriteGraphic>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export graphics::SpriteGraphic");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::SpriteLayer>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export graphics::SpriteLayer");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::TilePage>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export graphics::TilePage");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::ColorModificationTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export graphics::ColorModificationToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::ConditionTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export graphics::ConditionToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::GraphicTypeTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export graphics::GraphicTypeToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::GrowthTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export graphics::GrowthToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::PlantGraphicTemplateTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export graphics::PlantGraphicTemplateToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::TilePageTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export graphics::TilePageToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Inorganic>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export inorganic::Inorganic");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::EnvironmentClassTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export inorganic::EnvironmentClassToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::InclusionTypeTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export inorganic::InclusionTypeToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::InorganicTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export inorganic::Token");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Material>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export material::Material");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::FuelTypeTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export material::FuelTypeToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::MaterialPropertyTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export material::PropertyToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::MaterialStateTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export material::StateToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::MaterialTypeTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export material::TypeToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::MaterialUsageTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export material::UsageToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::MaterialTemplate>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export material_template::MaterialTemplate");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Plant>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export plant::Plant");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::PlantTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export plant::Token");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::PlantGrowth>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export plant_growth::PlantGrowth");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::PlantGrowthTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export plant_growth::Token");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::PlantGrowthTypeTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export plant_growth::TypeTokenn");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::PlantPartTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export plant_growth::PlantPartToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Position>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export position::Position");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::PositionTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export position::Token");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::SeedMaterial>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export seed_material::SeedMaterial");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::SelectCreature>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export select_creature::SelectCreature");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::SelectCreatureRuleTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export select_creature::SelectRules");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Shrub>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export shrub::Shru");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::SeasonTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export shrub::SeasonToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::ShrubTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export shrub::Token");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Syndrome>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export syndrome::Syndrome");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::SyndromeTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export syndrome::Token");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Tree>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export tree::Tree");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::TreeTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export tree::Token");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::TwigPlacementTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export tree::TwigPlacementToken");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::UnprocessedRaw>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export unprocessed_raw::UnprocessedRaw");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::tags::ModificationTag>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export Modification");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::MaterialMechanics>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::MaterialMechanics");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::metadata::RawMetadata>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::RawMetadata");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::InfoFile>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::ModuleInfoFile");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::SteamData>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::SteamData");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::StateNames>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::StateName");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::MechanicalProperties>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::MechanicalProperties");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Name>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::Name");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::metadata::ObjectType>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::ObjectType");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::metadata::RawModuleLocation>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::RawModuleLocation");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::BodySize>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::BodySize");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Color>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::Color");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Milkable>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::Milkable");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Temperatures>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::Temperatures");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Tile>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::Tile");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::Dimensions>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::Dimensions");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::CustomGraphicExtension>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::CustomGraphicExtension");
                eprintln!("{e:?}");
                String::new()
            }
        },
        // Tauri-specific exports
        match export::<dfraw_json_parser::metadata::ParserOptions>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::CustomGraphicExtension");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::ProgressDetails>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export progress::details::ProgressDetails");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::ProgressTask>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export progress::tasks::ProgressTask");
                eprintln!("{e:?}");
                String::new()
            }
        },
        match export::<dfraw_json_parser::ProgressPayload>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export progress::payload::ProgressPayload");
                eprintln!("{e:?}");
                String::new()
            }
        },
        // add the needed type RawModuleLocation
        match export::<dfraw_json_parser::metadata::RawModuleLocation>(&config) {
            Ok(x) => x,
            Err(e) => {
                eprintln!("Failed to export parser::RawModuleLocation");
                eprintln!("{e:?}");
                String::new()
            }
        },
    ];

    let missed = bindings.iter().filter(|x| x.is_empty()).collect::<Vec<_>>();
    // change missed into the number of missed bindings
    let missed = missed.len();
    // if there are missed bindings, print a warning
    if missed > 0 {
        eprintln!("Missed {missed} bindings");
    }

    // write the bindings to the output file
    ts_bindings.write(
        "Overseer's Manual rust type bindings",
        "Bindings.d.ts",
        None,
        &bindings.join("\n\n"),
    );
}
