// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CasteTag } from './CasteTag';
import type { CreatureTag } from './CreatureTag';
import type { InorganicToken } from './InorganicToken';

export type Filter = { creature: CreatureTag } | { creatureCaste: CasteTag } | { inorganic: InorganicToken } | 'none';
