// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Graphic,TilePage } from "./DFRawJson";


export interface GraphicsResults { matchingGraphics: Array<Graphic> | null, tilePages: Array<TilePage>, }
