// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Info {
  version: string;
  rustVersion: string;
  optimizationLevel: string;
  inDebug: boolean;
  dependencies: Array<[string, string]>;
  buildTime: string;
  gitCommitHash: string;
}
