// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectType,RawModuleLocation } from "./DFRawJson";

export interface Summary { totalRaws: number, counts: Array<[ObjectType, number]>, locationTotals: Array<[RawModuleLocation, number]>, parsingDuration: string, saveToStoreDuration: string, filteringDuration: string, objectsAllowed: Array<ObjectType>, locations: Array<RawModuleLocation>, }
