// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureVariationRule } from "./CreatureVariationRule";
import type { RawMetadata } from "./RawMetadata";

export interface CreatureVariation {
  metadata: RawMetadata;
  identifier: string;
  objectId: string;
  rules: Array<CreatureVariationRule>;
  argumentCount: number;
}
