// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureEffectProperty =
  | "Severity"
  | "Probability"
  | "Resistible"
  | "SizeDilutes"
  | "SizeDelays"
  | "Localized"
  | "VascularOnly"
  | "MuscularOnly"
  | "BodyPart"
  | "ByCategory"
  | "ByType"
  | "ByToken"
  | "Start"
  | "Peak"
  | "End"
  | "DwfStretch"
  | "AbruptStart"
  | "AbruptEnd"
  | "Abrupt"
  | "CanBeHidden"
  | "Unknown";
