// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphicType } from "./GraphicType";

export interface CustomGraphicExtension {
  extensionType: GraphicType;
  tilePageId: string;
  value1: number;
  value2: number;
}
