// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureTag } from "./CreatureTag";
import type { DFCaste } from "./DFCaste";
import type { DFTile } from "./DFTile";
import type { Name } from "./Name";
import type { RawMetadata } from "./RawMetadata";
import type { SingPlurName } from "./SingPlurName";

export interface DFCreature { metadata: RawMetadata, identifier: string, castes: Array<DFCaste>, tags: Array<CreatureTag>, biomes: Array<string>, prefStrings: Array<string>, tile: DFTile, frequency: number, clusterNumber: Array<number>, populationNumber: Array<number>, undergroundDepth: Array<number>, generalBabyName: SingPlurName, generalChildName: SingPlurName, name: Name, copyTagsFrom: string, applyCreatureVariation: Array<string>, objectId: string, }