// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DFColor } from "./DFColor";

export interface DFTile { character: string, altCharacter: string, color: DFColor, glowCharacter: string, glowColor: DFColor, }