// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnvironmentClass =
  | "AllStone"
  | "IgneousAll"
  | "IgneousExtrusive"
  | "IgneousIntrusive"
  | "Soil"
  | "SoilSand"
  | "SoilOcean"
  | "Sedimentary"
  | "Metamorphic"
  | "Alluvial"
  | "None";
