// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GaitType } from "./GaitType";
import type { Modifier } from "./Modifier";

export interface Gait {
  gaitType: GaitType;
  name: string;
  maxSpeed: number;
  energyUse: number;
  modifiers: Array<Modifier>;
}
