// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Graphic } from './Graphic';
import type { TilePage } from './TilePage';

export interface GraphicsResults {
  graphic: Graphic | null;
  tilePages: Array<TilePage>;
}
