// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphicGrowthTag = "Fruit" | "Growth1" | "Growth2" | "Growth3" | "Growth4" | "AsIs";
