// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GrowthTag =
  | "Growth"
  | "GrowthName"
  | "GrowthItem"
  | "GrowthHostTile"
  | "GrowthTrunkHeightPercent"
  | "GrowthDensity"
  | "GrowthTiming"
  | "GrowthPrint"
  | "GrowthHasSeed"
  | "GrowthDropsOff"
  | "GrowthDropsOffNoCloud"
  | "Unknown";
