// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GrowthType =
  | "Leaves"
  | "Spathes"
  | "Fruit"
  | "Flowers"
  | "Nut"
  | "SeedCatkins"
  | "PollenCatkins"
  | "Cone"
  | "SeedCone"
  | "PollenCone"
  | "Feathers"
  | "Eggs"
  | "Pod"
  | "None";
