// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentClass } from "./EnvironmentClass";
import type { InclusionType } from "./InclusionType";
import type { InorganicToken } from "./InorganicToken";
import type { Material } from "./Material";
import type { RawMetadata } from "./RawMetadata";

export interface Inorganic {
  identifier: string;
  metadata: RawMetadata;
  objectId: string;
  material: Material;
  metalOreChance: Array<[string, number]>;
  threadMetalChance: Array<[string, number]>;
  environmentClass: EnvironmentClass;
  environmentInclusionType: InclusionType;
  environmentInclusionFrequency: number;
  environmentClassSpecific: Array<string>;
  tags: Array<InorganicToken>;
}
