// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MaterialState =
  | "Solid"
  | "Liquid"
  | "Gas"
  | "Powder"
  | "Paste"
  | "Pressed"
  | "Unknown"
  | "All"
  | "AllSolid";
