// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Material } from "./Material";
import type { Metadata } from "./Metadata";

export interface MaterialTemplate {
  identifier: string;
  metadata: Metadata;
  objectId: string;
  material: Material;
}
