// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { FuelType } from "./FuelType";
import type { MaterialMechanics } from "./MaterialMechanics";
import type { StateName } from "./StateName";
import type { Syndrome } from "./Syndrome";
import type { Temperatures } from "./Temperatures";
import type { Tile } from "./Tile";
import type { Type } from "./Type";
import type { Usage } from "./Usage";

export interface Material {
  materialType: Type;
  name: string;
  fuelType: FuelType;
  creatureIdentifier: string;
  plantIdentifier: string;
  isLocalMaterial: boolean;
  reagentIdentifier: string;
  reactionProductIdentifier: string;
  templateIdentifier: string;
  usage: Array<Usage>;
  value: number;
  color: Color;
  stateNames: StateName;
  stateAdjectives: StateName;
  stateColors: StateName;
  temperatures: Temperatures;
  properties: Array<string>;
  syndromes: Array<Syndrome>;
  mechanicalProperties: MaterialMechanics;
  liquidDensity: number;
  molarMass: number;
  buildColor: Color;
  displayColor: Color;
  tile: Tile;
  itemSymbol: string;
}
