// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MechanicalProperties {
  yield: number;
  fracture: number;
  elasticity: number;
}
