// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Modifier =
  | "layersSlow"
  | "strength"
  | "agility"
  | { stealthSlows: { percentage: number } }
  | "noBuildUp"
  | { buildUp: { time: number; turning_max: number; start_speed: number } };
