// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Modification =
  | { copyTagsFrom: { identifier: string } }
  | { applyCreatureVariation: { identifier: string } }
  | { addToEnding: { raws: Array<string> } }
  | { addToBeginning: { raws: Array<string> } }
  | { addBeforeTag: { tag: string; raws: Array<string> } }
  | { mainRawBody: { raws: Array<string> } };
