// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RawModuleLocation } from "./RawModuleLocation";
import type { SteamData } from "./SteamData";

export interface ModuleInfoFile {
  identifier: string;
  objectId: string;
  location: RawModuleLocation;
  parentDirectory: string;
  numericVersion: number;
  displayedVersion: string;
  earliestCompatibleNumericVersion: number;
  earliestCompatibleDisplayedVersion: string;
  author: string;
  name: string;
  description: string;
  requiresIds: Array<string>;
  conflictsWithIds: Array<string>;
  requiresIdsBefore: Array<string>;
  requiresIdsAfter: Array<string>;
  steamData: SteamData;
}
