// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlantTag =
  | "Dry"
  | "Evil"
  | "Good"
  | "Savage"
  | "Wet"
  | "UndergroundDepth"
  | "Biome"
  | "Frequency"
  | "UseMaterialTemplate"
  | "BasicMaterial"
  | "UseMaterial"
  | "Material"
  | "PrefString"
  | "AllNames"
  | "NameAdjective"
  | "NamePlural"
  | "NameSingular"
  | "Unknown";
