// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlantGraphicTemplate =
  | "StandardLeaves"
  | "StandardFruit1"
  | "StandardFruit2"
  | "StandardFruit3"
  | "StandardFruit4"
  | "StandardFlowers1"
  | "StandardFlowers2"
  | "StandardFlowers3"
  | "StandardFlowers4";
