// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Material } from "./Material";
import type { Name } from "./Name";
import type { PlantGrowth } from "./PlantGrowth";
import type { PlantTag } from "./PlantTag";
import type { RawMetadata } from "./RawMetadata";
import type { Shrub } from "./Shrub";
import type { Tree } from "./Tree";

export interface Plant {
  metadata: RawMetadata;
  identifier: string;
  objectId: string;
  name: Name;
  prefStrings: Array<string>;
  tags: Array<PlantTag>;
  undergroundDepth: Array<number>;
  frequency: number;
  biomes: Array<string>;
  growths: Array<PlantGrowth>;
  treeDetails?: Tree;
  shrubDetails?: Shrub;
  materials: Array<Material>;
}
