// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectType } from "./ObjectType";
import type { RawModuleLocation } from "./RawModuleLocation";

export interface RawMetadata {
  moduleObjectId: string;
  moduleName: string;
  moduleVersion: string;
  rawFilePath: string;
  rawIdentifier: string;
  objectType: ObjectType;
  rawModuleLocation: RawModuleLocation;
}
