// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DFColor } from "./DFColor";
import type { SingPlurName } from "./SingPlurName";

export interface SeedMaterial {
  name: SingPlurName;
  color: DFColor;
  material: string;
}
