// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RawMetadata } from "./RawMetadata";

export interface SelectCreature {
  metadata: RawMetadata;
  identifier: string;
  objectId: string;
  tags: Array<string>;
}
