// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dimensions } from "./Dimensions";
import type { LayerCondition } from "./LayerCondition";

export interface SpriteLayer {
  layerName: string;
  tilePageId: string;
  offset: Dimensions;
  conditions: Array<[LayerCondition, number]>;
}
