// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dimensions } from "./Dimensions";
import type { GraphicCondition } from "./GraphicCondition";

export interface SpriteLayer {
  layerName: string;
  tilePageId: string;
  offset: Dimensions;
  offset2: Dimensions;
  largeImage: boolean;
  conditions: Array<[GraphicCondition, string]>;
}
