// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorModification } from "./ColorModification";
import type { Condition } from "./Condition";
import type { Dimensions } from "./Dimensions";

export interface SpriteGraphic {
  primaryCondition: Condition;
  tilePageId: string;
  offset: Dimensions;
  color: ColorModification;
  largeImage: boolean;
  offset2: Dimensions;
  secondaryCondition: Condition;
  colorPalletSwap: number;
  targetIdentifier: string;
  extraDescriptor: string;
}
