// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SteamData {
  title: string;
  description: string;
  tags: Array<string>;
  keyValueTags: Array<string>;
  metadata: Array<string>;
  changelog: string;
  fileId: bigint;
}
