// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyndromeToken =
  | "Name"
  | "Class"
  | "Injected"
  | "Contact"
  | "Inhaled"
  | "Ingested"
  | "AffectedClass"
  | "ImmuneClass"
  | "AffectedCreature"
  | "ImmuneCreature"
  | "ConcentrationAdded"
  | "NoHospital"
  | "Identifier"
  | "Unknown";
