// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Temperatures {
  specificHeat: number;
  ignitionPoint: number;
  meltingPoint: number;
  boilingPoint: number;
  heatDamagePoint: number;
  coldDamagePoint: number;
  materialFixedTemperature: number;
}
