// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

export interface Tile {
  character: string;
  altCharacter: string;
  color: Color;
  glowCharacter: string;
  glowColor: Color;
}
