// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dimensions } from "./Dimensions";
import type { Metadata } from "./Metadata";

export interface TilePage {
  metadata: Metadata;
  identifier: string;
  objectId: string;
  file: string;
  tileDim: Dimensions;
  pageDim: Dimensions;
}
