// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { Name } from "./Name";
import type { TreeToken } from "./TreeToken";
import type { TwigPlacement } from "./TwigPlacement";

export interface Tree {
  material: string;
  trunkName: Name;
  maxTrunkHeight: number;
  maxTrunkDiameter: number;
  trunkPeriod: number;
  trunkWidthPeriod: number;
  branchName: Name;
  branchDensity: number;
  branchRadius: number;
  heavyBranchesName: Name;
  heavyBranchDensity: number;
  heavyBranchRadius: number;
  trunkBranching: number;
  rootName: Name;
  rootDensity: number;
  rootRadius: number;
  twigsName: Name;
  twigsPlacement: Array<TwigPlacement>;
  capName: Name;
  capPeriod: number;
  capRadius: number;
  treeTile: string;
  deadTreeTile: string;
  saplingTile: string;
  deadSaplingTile: string;
  treeColor: Color;
  deadTreeColor: Color;
  saplingColor: Color;
  deadSaplingColor: Color;
  saplingDrownLevel: number;
  treeDrownLevel: number;
  tags: Array<TreeToken>;
}
