name: Dependabot Automation
on: pull_request

permissions: read-all

jobs:
  dependabot:
    name: Automerge Dependabot PRs (if possible)
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@0fb21704c18a42ce5aa8d720ea4b912f5e6babef #v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN  }}"
      - name: Install bun
        uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135 #v1
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Check if lockfile changed (package.json version changes)
        id: check-lockfile
        run: |
          bun install
          if [[ -n $(git status --porcelain) ]]; then
              echo "changes=true" >> "$GITHUB_OUTPUT";
          fi
      - name: Update bun.lockb
        if: steps.check-lockfile.outputs.changes == 'true'
        run: |
          git add bun.lockb
          git config --global user.name 'dependabot[bot]'
          git config --global user.email 'dependabot[bot]@users.noreply.github.com'
          git commit --amend --no-edit
          git push --force
      - name: Enable auto-merge for semver-path, semver-minor Dependabot PRs
        if: contains(steps.metadata.outputs.dependency-names, 'my-dependency') && (steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor')
        run: |
          gh pr merge --auto --merge "$PR_URL"
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.PAT_GH_TOKEN}}
      - name: Approve Github Actions PRs
        if: contains(github.event.pull_request.labels.*.name, 'github-actions')
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.PAT_GH_TOKEN}}
