name: 'Semantic Release'
on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: pnpm
      - name: process semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g pnpm
          pnpm install
          pnpm semantic-release
